# Generated by Django 4.0.5 on 2022-06-22 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]


    operations = [
        migrations.AlterField(
            model_name='projectgoal',
            name='name',
            field=models.CharField(max_length=81),
        ),
    ]
