# Generated by Django 4.0.5 on 2022-06-22 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_projectgoal_name'),
    ]

    def populate_goals_table(apps, schema_editor):
        #get ProjectGoal model
        ProjectGoal = apps.get_model('projects', 'ProjectGoal')

        goals = [
            'No poverty',
            'Zero hunger',
            'Good health and well-being',
            'Quality education',
            'Gender equality',
            'Clean water and sanitation',
            'Affordable and clean energy',
            'Decent work and economic growth',
            'Industry, innovation, and infrastructure',
            'Reduces inequalities',
            'Sustainable cities and communities',
            'Responsible consumption & production',
            'Climate action',
            'Life below water',
            'Life on land',
            'Peace, justice, and strong institutions'
        ]

        for goal in goals:
            ProjectGoal.objects.create(
                name=goal,
            )

    operations = [
        migrations.AlterField(
            model_name='projectgoal',
            name='name',
            field=models.CharField(max_length=80),
        ),
        migrations.RunPython(populate_goals_table),
    ]
